module.exports =  {
    1: [{
      "id":3,
      "restaurant_id":1,
      "name":"Barbabietola",
      "description":"roasted beets, goat yoghurt, almond & pistashio dressing",
      "price":"15.00"},
      {"id":1,
      "restaurant_id":1,
      "name":"Burrata con Carciofi",
      "description":"shaved artichoke salad, pecorino romano, black pepper, lemon",
      "price":"24.00"},
      {"id":2,
      "restaurant_id":1,
      "name":"Cesare",
      "description":"baby romaine, focaccia crumbs, pickled white anchovies, parmiggiano, pancetta, caesar dressing",
      "price":"15.00"},
      {"id":6,
      "restaurant_id":1,
      "name":"Conchiglie e Pistacchio",
      "description":"shell shaped pasta, pistachio pesto, garlic, baby shrimp, orange zest, basil",
      "price":"25.00"},
      {"id":5,
      "restaurant_id":1,
      "name":"Linguine al Pomodoro",
      "description":"yellow tomato pasta, cherry tomatoes, parmigiana, basil",
      "price":"19.00"},
      {"id":4,
      "restaurant_id":1,
      "name":"Piemonte",
      "description":"flor di latte, truffle crema, roasted garlic, mix mushroom, tomato cheese",
      "price":"21.00"}
    ],
    2: [{
      "id":11,
      "restaurant_id":2,
      "name":"Arroz Con Pollo",
      "description":"roasted chicken supreme, avocado rice, peas & corn, saffron chicken jus, tostones",
      "price":"29.00"},
      {"id":12,
      "restaurant_id":2,
      "name":"Big Ass Steak",
      "description":"roasted bone-in ribeye, chimichurri, veggies",
      "price":"120.00"},
      {"id":9,
      "restaurant_id":2,
      "name":"Campechano",
      "description":"shrimp, scallop, octopus, tomato, Valentina, olive, avocado, celery, citrus, cilantro, corn tortillas",
      "price":"22.00"},
      {"id":10,
      "restaurant_id":2,
      "name":"Cavatelli",
      "description":"Fresh pasta + piquillo peppers + charred corn + scallions + popcorn cream, queso fresco, pecorino, lime",
      "price":"19.00"},
      {"id":7,
      "restaurant_id":2,
      "name":"Harvest Ceviche",
      "description":"swordfish, yellow tomato, chill, basil, jicama, chulpes, plantain",
      "price":"24.00"},
      {"id":8,
      "restaurant_id":2,
      "name":"Tiradito",
      "description":"albacore tuna, passion fruit & lull, potato, squash, chili, cilantro,sesame seeds",
      "price":"21.00"}
    ],
    3: [{
      "id":16,
      "restaurant_id":3,
      "name":"Asian Crab Cakes With Smoked Kielbasa & Machego Cheese",
      "description":"manchego, green apple & Japanese cabbage kimchi, arugula",
      "price":"30.00"},
      {"id":18,
      "restaurant_id":3,
      "name":"Australian Wagyu Beef Carpaccio & Burrata",
      "description":"sweet onion, pickled mustard seeds, pumpkin seed oil, homemade gherkins, capers, heirloom beet",
      "price":"29.00"},
      {"id":17,
      "restaurant_id":3,
      "name":"Char Sui Duck Breast & Confit",
      "description":"Beijing duck garnish, foie gras pate, steamed pancake",
      "price":"36.00"},
      {"id":15,
      "restaurant_id":3,
      "name":"Spicy Crispy Tofu",
      "description":"mushroom & pepper compote, wildflower honey soya chili glaze, golden sand, watermelon radish",
      "price":"16.00"},
      {"id":14,
      "restaurant_id":3,
      "name":"Vegetarian Cheese Burger Spring Roll",
      "description":"sweet chili sauce, pickled veg, lettuce wrap",
      "price":"14.00"},
      {"id":13,
      "restaurant_id":3,
      "name":"Vietnamese Fresh Roll",
      "description":"tofu, avocado, kombucha, thai basil, pickled radish, sesame dip",
      "price":"14.00"}
    ]
  }
